"""Faiss index module.

Provides the core logic for faiss index.
"""

import faiss
import pickle
import os
import numpy as np


class FAISSIndex:
    """Encapsulates faissindex for this subsystem."""
    def __init__(self, dim: int):
        """Initialize a new instance with the provided dependencies and configuration.
        
        Args:
            dim: Input used to execute this operation.
        
        Returns:
            Result generated by this operation, when applicable.
        """
        self.dim = dim
        self.index = faiss.IndexFlatIP(dim)                     
        self.metadata = []

    def add(self, vectors, metadatas):
        """Handle add for this module.
        
        Args:
            vectors: Input used to execute this operation.
            metadatas: Input used to execute this operation.
        
        Returns:
            Result generated by this operation, when applicable.
        """
        self.index.add(np.array(vectors).astype("float32"))
        self.metadata.extend(metadatas)

    def search(self, query_vector, top_k=5):
        """Handle search for this module.
        
        Args:
            query_vector: Input used to execute this operation.
            top_k: Input used to execute this operation.
        
        Returns:
            Result generated by this operation, when applicable.
        """
        scores, indices = self.index.search(
            np.array([query_vector]).astype("float32"), top_k
        )
        results = []
        for idx, score in zip(indices[0], scores[0]):
            if idx == -1:
                continue
            results.append({
                "score": float(score),
                "metadata": self.metadata[idx]
            })
        return results

    def save(self, index_path, metadata_path):
        """Handle save for this module.
        
        Args:
            index_path: Input used to execute this operation.
            metadata_path: Input used to execute this operation.
        
        Returns:
            Result generated by this operation, when applicable.
        """
        faiss.write_index(self.index, index_path)
        with open(metadata_path, "wb") as f:
            pickle.dump(self.metadata, f)

    def load(self, index_path, metadata_path):
        """Load data from the configured source.
        
        Args:
            index_path: Input used to execute this operation.
            metadata_path: Input used to execute this operation.
        
        Returns:
            Result generated by this operation, when applicable.
        """
        self.index = faiss.read_index(index_path)
        with open(metadata_path, "rb") as f:
            self.metadata = pickle.load(f)
