"""Excel loader module.

Provides the core logic for excel loader.
"""

import pandas as pd

def load_excel(path: str, sheet_name: str = "tbl_MY") -> pd.DataFrame:
    """Load excel from the configured source.
    
    Args:
        path: Input used to execute this operation.
        sheet_name: Input used to execute this operation.
    
    Returns:
        Result generated by this operation, when applicable.
    """
    df = pd.read_excel(path, sheet_name=sheet_name)
    df.columns = df.columns.str.strip()
    return df
